### ISSUE TITLE
Avaliação

### ISSUE THREAD

**Issue by dfiedlerx** [dfiedlerx/woocommerce-pagseguro-with-recurrence#1]
@claudiosanches @lwxbr Poderiam por favor dar uma olhada nesse plugin? Vi que muitas pessoas estavam procurando um nesse sentido que adiciona a possibilidade de recorrência. O código esta meio espaguete por causa do tempo que havia para desenvolver mas funciona perfeitamente.

**Comment by claudiosanches** [comment]
Esse plugin é um fork do meu do PagSeguro, mas eu não contribui com este plugin aqui, recorrencia é algo que eu devo implementar um dia no plugin do PagSeguro, preciso de tempo livre para isso.

**Comment by dfiedlerx** [comment]
@claudiosanches Pois se precisar de ajuda, eu praticamente ja implementei todo o fluxo aqui. Inclusive a possibilidade de cancelar a recorrencia no proprio wordpress. Usei uma biblioteca de php ja existente para desenvolver. Vi que um tempo atrás você criou um issue aberto a contribuições.

Como disse, muito aqui tem que ser melhorado por causa do prazo que eu tinha mas é totalmente possível. Algumas pessoas me procuraram pedindo ajuda para utilizar no projeto delas e funcionou perfeitamente.
